mappings:
  APIwesomeTokenExtension: nglasl\APIwesome\Extensions\APIwesomeTokenExtension
  ModelAdminPreviewExtension: nglasl\APIwesome\Extensions\ModelAdminPreviewExtension
  APIwesome: nglasl\APIwesome\Controllers\APIwesome
  APIwesomeAdmin: nglasl\APIwesome\Controllers\APIwesomeAdmin
  APIwesomeService: nglasl\APIwesome\Services\APIwesomeService
  APIwesomeToken: nglasl\APIwesome\Models\APIwesomeToken
  DataObjectOutputConfiguration: nglasl\APIwesome\Models\DataObjectOutputConfiguration
  APIwesomePreviewButton: nglasl\APIwesome\Forms\APIwesomePreviewButton
  APIwesomeTokenView: nglasl\APIwesome\Forms\APIwesomeTokenView
